import Link from 'next/link';
import HomeHeroSlideshow from '../components/HomeHeroSlideshow';
import DailyTipSpotlight from '../components/DailyTipSpotlight';
import { createClient } from '../lib/supabase/server';

export const dynamic = 'force-dynamic';

const fallbackSlides = [{
  id: 'fallback',
  title: 'Empowering communities. Creating lasting change.',
  subtitle: 'We work with underserved communities to expand opportunity through inclusive education, gender equity, better health, climate resilience and practical pathways to sustainable development.',
  image_path: '/assets/IMG-20260617-WA0018.jpg',
  image_url: '/assets/IMG-20260617-WA0018.jpg',
  button_text: 'Partner with GPDO',
  button_url: '/get-involved',
  secondary_button_text: 'Explore our work',
  secondary_button_url: '/programs',
  overlay_strength: 0.6,
}];

export default async function HomePage(){
  const supabase = await createClient();
  const [{ data: slideData }, { data: tipData }] = await Promise.all([
    supabase.from('home_slides').select('*').eq('is_active', true).order('sort_order').order('created_at'),
    supabase.from('daily_tips').select('*').eq('status','published').order('display_date',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false}).limit(1)
  ]);
  const now = Date.now();
  const managedSlides = (slideData || []).filter((slide) => (!slide.starts_at || new Date(slide.starts_at).getTime() <= now) && (!slide.ends_at || new Date(slide.ends_at).getTime() >= now));
  const heroSlides = managedSlides.length ? managedSlides : fallbackSlides;
  const dailyTip = tipData?.[0] || null;

  return <main>
<HomeHeroSlideshow slides={heroSlides}/>
<div className="donor-bar"><div className="container donor-panel"><div><div className="eyebrow">Built for responsible partnership</div><strong>Community-driven. Transparent. Sustainable.</strong></div><div className="seal"><div className="seal-icon">✓</div><div><div className="eyebrow">Governance</div><strong>Integrity-led</strong></div></div><div className="seal"><div className="seal-icon">◷</div><div><div className="eyebrow">Programmes</div><strong>Long-term focus</strong></div></div><div className="seal"><div className="seal-icon">⌂</div><div><div className="eyebrow">Partnerships</div><strong>Public + private</strong></div></div></div></div>
<DailyTipSpotlight tip={dailyTip}/>
<section className="section"><div className="container split reveal"><div className="photo-card"><img src="/assets/IMG-20260617-WA0014.jpg" alt="Community outreach and partnership activity" loading="lazy"/><div className="photo-badge"><strong>Development begins with people.</strong><span>We listen first, build with communities and design interventions around real needs and long-term ownership.</span></div></div><div><span className="kicker">Who we are</span><h2>Passion translated into practical development.</h2><p className="lead">GPDO is a non-profit organization committed to empowering marginalized communities through integrated and sustainable development initiatives.</p><p>We believe every person, regardless of background or circumstance, deserves access to quality education, healthcare, equal opportunity and a safe, sustainable environment. Our work is rooted in collaboration, ethical governance and solutions that communities can sustain.</p><Link className="btn btn-secondary" href="/about">Discover our story →</Link></div></div></section>
<section className="section bg-soft"><div className="container"><div className="eyebrow-row reveal"><div><span className="kicker">Our core focus areas</span><h2>Four priorities. One shared purpose.</h2></div><p className="lead">We address connected challenges together, because education, health, equality and environmental resilience are strongest when they advance side by side.</p></div><div className="grid-4">{[['Education & Capacity Development','Inclusive education, vocational skills, entrepreneurship and leadership pathways that strengthen self-reliance and economic opportunity.','education'],['Gender Equality & Social Inclusion','Advocacy and initiatives that expand opportunities for women and girls, protect vulnerable populations and advance social justice.','gender'],['Healthcare & Community Wellbeing','Preventive health awareness and community-based interventions that improve wellbeing and reduce inequalities in access to care.','health'],['Climate Action & Sustainable Development','Environmental education, community mobilization and practical sustainable solutions that protect current and future generations.','climate']].map(([t,d,id],i)=><article className="focus-card reveal" key={t}><div className="icon-box">{i+1}</div><h3>{t}</h3><p>{d}</p><Link href={`/programs#${id}`}>Learn more →</Link></article>)}</div></div></section>
<section className="section"><div className="container"><div className="eyebrow-row reveal"><div><span className="kicker">What we do</span><h2>From skills to wellbeing, we act where opportunity is constrained.</h2></div><p>Our programme portfolio is designed to be adaptable to local needs while remaining aligned with GPDO&apos;s wider development mission.</p></div><div className="what-grid">{[['01','Community empowerment','Locally informed initiatives that help communities shape and own the solutions affecting their future.'],['02','Entrepreneurship & skills','Practical training that supports employability, enterprise development and sustainable livelihoods.'],['03','Youth development','Opportunities that strengthen confidence, leadership, learning and productive participation.'],['04','Women & aged projects','Targeted support for women, girls and older persons, with dignity and inclusion at the centre.'],['05','Health outreach','Awareness and preventive interventions that bring practical health information closer to communities.'],['06','Climate advocacy','Mobilization and education that help communities understand and respond to climate-related risks.']].map(([n,t,d])=><div className="what-card reveal" key={n}><div className="what-num">{n}</div><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></div></section>
<section className="section bg-soft action-gallery"><div className="container"><div className="eyebrow-row reveal"><div><span className="kicker">Our work in action</span><h2>Community engagement, partnership and practical support.</h2></div><p className="lead">A glimpse of community outreach and engagement activities connected to GPDO&apos;s mission of serving people with dignity and purpose.</p></div><div className="gallery-preview"><figure className="gallery-feature reveal"><img src="/assets/IMG-20260617-WA0026.jpg" alt="Community outreach group with donated supplies"/><figcaption>Community outreach &amp; partnership</figcaption></figure><figure className="reveal"><img src="/assets/IMG-20260617-WA0014.jpg" alt="Community donation handover"/><figcaption>Partnership in action</figcaption></figure><figure className="reveal"><img src="/assets/IMG-20260617-WA0022.jpg" alt="GPDO team group portrait"/><figcaption>People behind the mission</figcaption></figure><figure className="reveal"><img src="/assets/IMG-20260617-WA0018.jpg" alt="Community group celebrating during outreach"/><figcaption>Shared community moments</figcaption></figure></div></div></section>
<section className="section approach"><div className="container reveal"><span className="kicker">How we work</span><h2>Participation first. Evidence always. Sustainability by design.</h2><p className="lead">Our approach combines local insight, cross-sector collaboration and accountable programme delivery so that solutions are relevant today and durable tomorrow.</p><div className="steps">{[['1','Listen locally','Work closely with communities to understand needs, barriers, assets and priorities.'],['2','Build partnerships','Collaborate with government, civil society and private institutions around shared outcomes.'],['3','Deliver responsibly','Promote accountability, transparency, ethical governance and practical execution.'],['4','Measure & improve','Design programmes with measurable objectives and a long-term sustainability lens.']].map(([n,t,d])=><div className="step" key={n}><div className="step-no">{n}</div><strong>{t}</strong><span>{d}</span></div>)}</div></div></section>
<section className="section"><div className="container story reveal"><div className="story-card dark"><span className="kicker" style={{color:'#dbeee9'}}>Our vision</span><p className="quote">A world where marginalized communities thrive through inclusive education, gender equality, quality healthcare, climate resilience and social justice.</p></div><div className="story-card"><span className="kicker">Why GPDO exists</span><h2 style={{fontSize:'clamp(1.9rem,3vw,2.8rem)'}}>Bridging gaps with community-driven solutions.</h2><p>Persistent barriers in education, healthcare, gender equality and climate resilience continue to limit opportunity in many communities. Founded in 2024 by Bishop Dr. Akoto and Rev. Mrs. Akoto, GPDO exists to complement government and partner efforts with practical, innovative programmes rooted in human dignity.</p><p><strong>Driven by passion. Guided by integrity. Committed to measurable transformation.</strong></p></div></div></section>
<section className="section-sm"><div className="container cta reveal"><div><span className="kicker" style={{color:'#fff'}}>Partner for impact</span><h2>Help communities turn potential into lasting progress.</h2><p>We welcome partnerships with foundations, companies, development agencies, public institutions, community organizations and individuals who share our commitment to inclusive, sustainable development.</p></div><div className="cta-actions"><Link className="btn btn-primary" href="/get-involved">Get involved</Link><Link className="btn btn-light" href="/contact">Contact GPDO</Link></div></div></section>
</main>}
