import Link from 'next/link';
import PageHero from '../../components/PageHero';
import { createClient } from '../../lib/supabase/server';

export const dynamic='force-dynamic';
export const metadata={title:'Our Work',description:'Explore GPDO programmes in education, gender equality, healthcare, climate action, youth development and community empowerment.'};
const focusAreas=[['01','education','Education','Education & Capacity Development','We promote access to inclusive and quality education, vocational training, entrepreneurship development and leadership programmes that equip individuals with practical skills for self-reliance and economic growth.',['Inclusive education','Vocational skills','Entrepreneurship','Youth leadership','Capacity building']],['02','gender','Inclusion','Gender Equality & Social Inclusion','We advocate for equal opportunities for women and girls while supporting initiatives that protect vulnerable populations, strengthen participation and advance social justice.',['Women empowerment',"Girls' opportunity",'Social inclusion','Aged support','Advocacy']],['03','health','Wellbeing','Healthcare & Community Wellbeing','We support healthcare awareness, preventive health initiatives and community-based interventions aimed at improving wellbeing and reducing inequalities in access to health services.',['Health awareness','Prevention','Community outreach','Wellbeing education','Referral partnerships']],['04','climate','Sustainability','Climate Action & Sustainable Development','We complement government and global efforts on climate change through community mobilization, environmental education and innovative sustainable solutions that protect present and future generations.',['Climate awareness','Environmental education','Community resilience','Sustainable practices','Mobilization']]];

const labelStatus=(value='')=>value.charAt(0).toUpperCase()+value.slice(1);
const formatDate=(value)=>value?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${value}T00:00:00`)):'';

export default async function ProgramsPage(){
  const supabase=await createClient();
  const {data}=await supabase.from('programs').select('*').eq('is_published',true).neq('status','archived').order('is_featured',{ascending:false}).order('created_at',{ascending:false});
  const managed=data||[];
  return <main><PageHero section="Our Work" title="Integrated programmes for stronger, more resilient communities." lead="Our focus areas respond to interconnected barriers that can hold communities back. We design solutions around practical needs, partnership and long-term sustainability."/>
    <section className="section"><div className="container program-list">{focusAreas.map(([n,id,kicker,title,desc,pills])=><article id={id} className="program-row reveal" key={id}><div className="program-index">{n}</div><div><span className="kicker">{kicker}</span><h2 style={{fontSize:'clamp(1.8rem,3vw,2.7rem)'}}>{title}</h2><p>{desc}</p></div><div><h3>Programme directions</h3><div className="pill-wrap">{pills.map(p=><span className="pill" key={p}>{p}</span>)}</div></div></article>)}</div></section>
    {managed.length>0&&<section className="section managed-programs"><div className="container"><div className="managed-programs-head reveal"><div><span className="kicker">Current portfolio</span><h2>Programmes & projects in action.</h2></div><p>Explore GPDO initiatives that are upcoming, ongoing or completed, including the communities, partners and development priorities behind them.</p></div><div className="managed-program-grid">{managed.map(program=><article className={`managed-program-card reveal${program.is_featured?' featured':''}`} key={program.id}><div className="managed-program-image">{program.featured_image_url&&<img src={program.featured_image_url} alt={program.title}/>}<span className="program-card-status">{labelStatus(program.status)}</span></div><div className="managed-program-body"><span className="kicker">{program.focus_area||'GPDO Programme'}</span><h3>{program.title}</h3><p>{program.summary||'Learn more about this GPDO programme and its intended community impact.'}</p><div className="managed-program-meta">{program.location&&<span>{program.location}</span>}{program.start_date&&<span>{formatDate(program.start_date)}{program.end_date?` – ${formatDate(program.end_date)}`:''}</span>}</div><Link href={`/programs/${program.slug}`}>View programme →</Link></div></article>)}</div></div></section>}
    <section className="section bg-soft"><div className="container"><div className="eyebrow-row reveal"><div><span className="kicker">Programme model</span><h2>How a GPDO initiative is shaped.</h2></div><p className="lead">Each intervention can be adapted to the community and partner context while keeping a consistent commitment to relevance, accountability and sustainability.</p></div><div className="steps" style={{color:'var(--ink)'}}>{[['1','Needs & context','Understand the issue, local assets, risks and intended beneficiaries.'],['2','Co-design','Develop practical objectives, roles and delivery methods with communities and partners.'],['3','Implementation','Deliver activities with responsible stewardship, local participation and clear coordination.'],['4','Learning & continuity','Track results, learn from implementation and strengthen pathways for continuity.']].map(([n,t,d])=><div className="step" style={{background:'#fff',borderColor:'var(--line)'}} key={n}><div className="step-no">{n}</div><strong>{t}</strong><span style={{color:'var(--muted)'}}>{d}</span></div>)}</div></div></section>
    <section className="section-sm"><div className="container cta reveal"><div><span className="kicker" style={{color:'#fff'}}>Co-create a programme</span><h2>Have a priority community, issue or funding theme?</h2><p>GPDO can explore programme concepts with institutional partners across our four core focus areas.</p></div><div className="cta-actions"><Link className="btn btn-primary" href="/contact">Discuss a partnership</Link></div></div></section>
  </main>;
}
