'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { createClient } from '../../../lib/supabase/client';

const blank={title:'',tip:'',category:'Education',display_date:'',status:'draft',image_path:'',image_url:''};
const safeFileName=(name='')=>name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/-+/g,'-');
const messageFor=(error)=>error?.message||'Something went wrong. Please try again.';
const categories=['Education','Health','Women & Girls','Youth','Climate','Entrepreneurship','Leadership','Community Development'];

export default function DailyTipsManager({adminRole}){
  const supabase=useMemo(()=>createClient(),[]);
  const [tips,setTips]=useState([]);const [media,setMedia]=useState([]);const [form,setForm]=useState(blank);const [file,setFile]=useState(null);const [busy,setBusy]=useState(true);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');
  const flash=(text,isError=false)=>{if(isError){setError(text);setNotice('')}else{setNotice(text);setError('')}window.setTimeout(()=>{setNotice('');setError('')},5000)};
  const loadData=useCallback(async()=>{setBusy(true);const [tipsResult,mediaResult]=await Promise.all([
    supabase.from('daily_tips').select('*').order('display_date',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false}),
    supabase.from('media').select('id,title,public_url,file_path').eq('is_published',true).order('sort_order').order('created_at',{ascending:false})
  ]);const firstError=tipsResult.error||mediaResult.error;if(firstError)flash(messageFor(firstError),true);setTips(tipsResult.data||[]);setMedia(mediaResult.data||[]);setBusy(false)},[supabase]);
  useEffect(()=>{loadData()},[loadData]);

  async function uploadImage(selectedFile){if(!selectedFile)return{path:'',url:''};if(!selectedFile.type.startsWith('image/'))throw new Error('Please choose an image file.');if(selectedFile.size>10*1024*1024)throw new Error('Tip image must be 10 MB or smaller.');const folder=new Date().toISOString().slice(0,7);const unique=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;const path=`tips/${folder}/${unique}-${safeFileName(selectedFile.name)}`;const{error:uploadError}=await supabase.storage.from('media').upload(path,selectedFile,{cacheControl:'3600',upsert:false});if(uploadError)throw uploadError;const{data}=supabase.storage.from('media').getPublicUrl(path);return{path,url:data.publicUrl}}
  function chooseMedia(id){const item=media.find((m)=>m.id===id);setFile(null);const picker=document.getElementById('gpdo-tip-image');if(picker)picker.value='';if(!item)return setForm((v)=>({...v,image_path:'',image_url:''}));setForm((v)=>({...v,image_path:item.file_path,image_url:item.public_url}))}
  async function createTip(e){e.preventDefault();if(!form.tip.trim())return flash('Enter the tip text.',true);setSaving(true);let uploaded=null;try{let imagePath=form.image_path,imageUrl=form.image_url;if(file){uploaded=await uploadImage(file);imagePath=uploaded.path;imageUrl=uploaded.url}const{error:insertError}=await supabase.from('daily_tips').insert({title:form.title.trim()||null,tip:form.tip.trim(),category:form.category||null,image_path:imagePath||null,image_url:imageUrl||null,display_date:form.display_date||null,status:form.status});if(insertError)throw insertError;setForm(blank);setFile(null);const picker=document.getElementById('gpdo-tip-image');if(picker)picker.value='';flash('Daily tip created.');await loadData()}catch(e2){if(uploaded?.path)await supabase.storage.from('media').remove([uploaded.path]);flash(messageFor(e2),true)}finally{setSaving(false)}}
  async function saveTip(id,values){const{error:updateError}=await supabase.from('daily_tips').update({...values,title:values.title?.trim()||null,tip:values.tip.trim(),category:values.category||null,display_date:values.display_date||null,updated_at:new Date().toISOString()}).eq('id',id);if(updateError)return flash(messageFor(updateError),true);flash('Tip saved.');await loadData()}
  async function replaceImage(tip,selectedFile){try{const uploaded=await uploadImage(selectedFile);const oldPath=tip.image_path;const{error:updateError}=await supabase.from('daily_tips').update({image_path:uploaded.path,image_url:uploaded.url,updated_at:new Date().toISOString()}).eq('id',tip.id);if(updateError){await supabase.storage.from('media').remove([uploaded.path]);throw updateError}if(oldPath?.startsWith('tips/'))await supabase.storage.from('media').remove([oldPath]);flash('Tip image updated.');await loadData()}catch(e){flash(messageFor(e),true)}}
  async function deleteTip(tip){if(!window.confirm('Delete this daily tip?'))return;const{error:deleteError}=await supabase.from('daily_tips').delete().eq('id',tip.id);if(deleteError)return flash(messageFor(deleteError),true);if(tip.image_path?.startsWith('tips/'))await supabase.storage.from('media').remove([tip.image_path]);flash('Tip deleted.');await loadData()}
  const today=new Date().toISOString().slice(0,10);const counts=useMemo(()=>({published:tips.filter(t=>t.status==='published').length,drafts:tips.filter(t=>t.status==='draft').length,scheduled:tips.filter(t=>t.status==='published'&&t.display_date&&t.display_date>today).length}),[tips,today]);

  return <div className="tip-manager">{(notice||error)&&<div className={error?'media-alert error':'media-alert success'}>{error||notice}</div>}
    <div className="tip-stats"><div><span>All tips</span><strong>{tips.length}</strong></div><div><span>Published</span><strong>{counts.published}</strong></div><div><span>Drafts</span><strong>{counts.drafts}</strong></div><div><span>Scheduled ahead</span><strong>{counts.scheduled}</strong></div></div>
    <section className="media-panel"><div className="media-panel-heading"><div><span className="admin-eyebrow">Create Tip</span><h2>Prepare daily guidance</h2><p>Choose a future date to schedule a published tip in advance.</p></div><span className="media-role-badge">{adminRole}</span></div>
      <form className="tip-create-form" onSubmit={createTip}>
        <label>Optional title<input value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))} placeholder="e.g. Healthy Habit of the Day" /></label>
        <label>Category<select value={form.category} onChange={e=>setForm(v=>({...v,category:e.target.value}))}>{categories.map(c=><option key={c}>{c}</option>)}</select></label>
        <label className="tip-full">Tip text<textarea rows="5" value={form.tip} onChange={e=>setForm(v=>({...v,tip:e.target.value}))} placeholder="Write one clear, practical tip." /></label>
        <label>Display date<input type="date" value={form.display_date} onChange={e=>setForm(v=>({...v,display_date:e.target.value}))} /></label>
        <label>Status<select value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value}))}><option value="draft">Draft</option><option value="published">Published / Scheduled</option><option value="archived">Archived</option></select></label>
        <label>Choose from Media Library<select value="" onChange={e=>chooseMedia(e.target.value)}><option value="">Optional image…</option>{media.map(m=><option key={m.id} value={m.id}>{m.title||'Untitled image'}</option>)}</select></label>
        <label>Or upload image<input id="gpdo-tip-image" type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)} /></label>
        {(form.image_url||file)&&<div className="tip-image-preview tip-full">{form.image_url&&!file?<img src={form.image_url} alt="Selected tip" />:<strong>{file?.name}</strong>}</div>}
        <div className="tip-full"><button className="admin-primary-btn" disabled={saving}>{saving?'Saving tip…':'Create daily tip'}</button></div>
      </form>
    </section>
    <section className="media-panel"><div className="media-panel-heading"><div><span className="admin-eyebrow">Tip Library</span><h2>{tips.length} tip{tips.length===1?'':'s'}</h2><p>Future scheduled tips stay private until their display date.</p></div><button className="admin-secondary-btn" type="button" onClick={loadData}>Refresh</button></div>
      {busy?<div className="media-empty">Loading tips…</div>:tips.length===0?<div className="media-empty"><strong>No daily tips yet.</strong><span>Create tips above and schedule them when ready.</span></div>:<div className="tip-list">{tips.map(tip=><TipEditor key={tip.id} tip={tip} media={media} onSave={saveTip} onDelete={deleteTip} onReplaceImage={replaceImage} />)}</div>}
    </section>
  </div>
}

function TipEditor({tip,media,onSave,onDelete,onReplaceImage}){const[draft,setDraft]=useState({title:tip.title||'',tip:tip.tip||'',category:tip.category||'',display_date:tip.display_date||'',status:tip.status||'draft',image_path:tip.image_path||'',image_url:tip.image_url||''});useEffect(()=>setDraft({title:tip.title||'',tip:tip.tip||'',category:tip.category||'',display_date:tip.display_date||'',status:tip.status||'draft',image_path:tip.image_path||'',image_url:tip.image_url||''}),[tip]);function chooseExisting(id){const item=media.find(m=>m.id===id);if(item)setDraft(v=>({...v,image_path:item.file_path,image_url:item.public_url}))}return <article className="tip-editor"><div className="tip-editor-head">{draft.image_url?<img src={draft.image_url} alt="Tip" />:<div className="tip-no-image">TIP</div>}<div><span className={`tip-status ${draft.status}`}>{draft.status}</span><h3>{draft.title||draft.category||'Daily tip'}</h3><p>{draft.display_date||'No display date'}</p></div></div><div className="tip-edit-grid"><label>Title<input value={draft.title} onChange={e=>setDraft(v=>({...v,title:e.target.value}))} /></label><label>Category<input value={draft.category} onChange={e=>setDraft(v=>({...v,category:e.target.value}))} /></label><label className="tip-full">Tip<textarea rows="4" value={draft.tip} onChange={e=>setDraft(v=>({...v,tip:e.target.value}))} /></label><label>Display date<input type="date" value={draft.display_date} onChange={e=>setDraft(v=>({...v,display_date:e.target.value}))} /></label><label>Status<select value={draft.status} onChange={e=>setDraft(v=>({...v,status:e.target.value}))}><option value="draft">Draft</option><option value="published">Published / Scheduled</option><option value="archived">Archived</option></select></label><label>Use Media Library<select value="" onChange={e=>chooseExisting(e.target.value)}><option value="">Choose image…</option>{media.map(m=><option key={m.id} value={m.id}>{m.title||'Untitled image'}</option>)}</select></label><label>Replace image<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)onReplaceImage(tip,f);e.target.value=''}} /></label></div><div className="tip-actions"><button className="admin-primary-btn" type="button" onClick={()=>onSave(tip.id,draft)}>Save changes</button><button className="media-danger-btn" type="button" onClick={()=>onDelete(tip)}>Delete tip</button></div></article>}
